import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Stock } from '../../models/stock';
import { StockService } from '../../services/stock.service';
import { NgxPaginationModule } from 'ngx-pagination'; // This code was generated by GitHub Copilot

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, NgxPaginationModule], // This code was generated by GitHub Copilot
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  p: number = 1;


  //countries  array to store india,china,germany,usa,australia,japan
  countries = ['India', 'China', 'Germany', 'USA', 'Australia', 'Japan'];
  stocks: Stock[] = [];
  message: string = '';

  //inject the stock service in the constructor of the component
  constructor(private stockService: StockService) { }

  //onInit function to get all the stocks by country 
  ngOnInit() {
    this.getAllStocksByCountry();
  }


  //getAllStocksByCountry function to get all the stocks by country using the stock service and store the stocks in the stocks array.  pass country as a parameter
  getAllStocksByCountry(country: string = 'India') {
    this.stockService.getAllStocksByCountry(country).subscribe({
      next: (response: any) => {
        console.log(response.data);
        this.stocks = response.data;
      },
      error: (error) => {
        console.log(error)
      },
      complete: () => {
        console.log('complete')
      }
    });
  }
  //function addTowishList to add a stock to the wishlist using stockservice. pass stock as a parameter. 
  addToWishList(stock: Stock) {
    this.stockService.addToWishList(stock).subscribe({
      next: (response: any) => {
        console.log(response);
        this.message = 'Stock added to wishlist';
        alert(this.message);
      },
      error: (error) => {
        console.log(error)
      },
      complete: () => {
        console.log('complete')
      }
    });
  }
  getStocksByPage(page: any) {
    throw new Error('Method not implemented.');
  }


}
