import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class StockService {
  //define the base url of the API from the  environment file

  baseUrl = environment.baseUrl;


  //inject the HttpClient service in the constructor  of the service
  constructor(private http: HttpClient) {
    console.log(this.baseUrl)
  }

  // function  getAllStocksByCountry to get all the stocks by country. pass country as a parameter
  getAllStocksByCountry(country: string) {
    console.log(`${this.baseUrl}?country=${country}`)
    return this.http.get(`${this.baseUrl}?country=${country}`);
  }

  //function getStocksFromWishList  to get all the stocks from the  json-server which is running in http://localhost:3000/wishlist 

  //function getStocksFromWishList  to get all the stocks from the  json-server which is running in http://localhost:3000/wishlist 
  getStocksFromWishList() {
    return this.http.get('http://localhost:3000/wishlist'); // This code was generated by GitHub Copilot
  }



}

